### ISSUE TITLE
Sequential images before random

### ISSUE THREAD

**Issue by FreshieGeek** [cmrazek/WallSwitch#1]
Hi. Freshie@Gmail.com again.
There used to be an option to display a few images in a row before choosing another random starting image.
I don't see that option any more. Have you removed it? I had it set to three before the update, and I'm still getting three, but I don't see where I could change it to one or four..

**Comment by cmrazek** [comment]
Oops, those controls are getting hidden by the new layout. I'll get that fixed.

**Comment by cmrazek** [comment]
Version 1.6.2 should fix this. Thanks for reporting it.
