### ISSUE TITLE
deleting a file

### ISSUE THREAD

**Issue by FreshieGeek** [cmrazek/WallSwitch#2]
Whenever I delete a file through wall Switch, and sometime when I miss click and hit an empty area in the thumbnail disply, I get this error pop up. Since I'm here, is there a way to make the thumbnails bigger?
![Screenshot 2020-11-15 141253](https://user-images.githubusercontent.com/18175874/99194317-b1dd4c00-274c-11eb-95ed-b15fe9f1ac05.png)

**Comment by cmrazek** [comment]
I've added some fixes which should suppress those errors. The errors themselves are harmless (just annoying), so I'll leave this fix to be included with the next version, whenever that may be.

Thumbnail size is currently hard-coded to fit in a 120x120 rectangle. Making them larger in the UI would show poor image quality when stretched bigger. Avoiding that would require significant rework to dynamically resize the cached thumbnails on display. That may be something I can look at later, but can't promise anything at this time.

**Comment by FreshieGeek** [comment]
I know it might be a bit of a rebuild, but why can't I just drag an image
from the history into another program?
Regardless of why, I'd REALLY like to be able to drag from into
something/anything else.
I use your program daily. I'll buy it if you ask for payment, but i'd
really like to drag from the history tab to the rest of Windows.

**Comment by cmrazek** [comment]
Ok, I've added a drag-drop feature from the history list. v1.6.3

Just so you know... this uses the same behaviour as the Windows file-drag. So if you drag with your left mouse button to a Windows Explorer at another location on the same drive as a the original image, it will MOVE the file, not copy. If you want to COPY the file, drag with your right mouse button and then select 'Copy here' on the context menu that pops up when you finish your drag.

**Comment by FreshieGeek** [comment]
Awesome. Thank you very much!

**Comment by FreshieGeek** [comment]
Hi! It's been a while.
Could you please carry the paused or not on restart?
Thank you.
Cheers!
