### ISSUE TITLE
Clear History..

### ISSUE THREAD

**Issue by FreshieGeek** [cmrazek/WallSwitch#3]
When I select Clear history form the tools menu, it clears both the history, and the screen.
When I use the hotkey, it clears the history in the program, but doesn't clear the screen.
In the next update, please make the hotkey clear the screen as well.
Thanks!

**Comment by FreshieGeek** [comment]
Sorry, It does clear the history, but only on the next change.
I'd like it to be immediate, the same as the menu does.
Thanks.

**Comment by cmrazek** [comment]
As of version 1.6.4, the screen will now be cleared when using either the menu or the hotkey. Thanks.
