### ISSUE TITLE
Automated tasks interrupted

### ISSUE THREAD

**Issue by FreshieGeek** [cmrazek/WallSwitch#5]
I have things set to run after the computer is idle for 5 minutes, and I have WS set to change every 90 seconds. It seems that the WS change is triggering user use, which resets the computer being considered idle.

**Comment by cmrazek** [comment]
Depending on how you set your tasks to run on idle (e.g. Task Scheduler), this may just be a side-effect of how it detects when your computer is idle:
https://docs.microsoft.com/en-us/windows/win32/taskschd/task-idle-conditions

"The computer is considered idle if all the processors and all the disks were idle for more than 90% of the last detection interval"

Every time a 'switch' occurs, WallSwitch needs to load images from disk, render the images, apply background effects (if in collage mode), and render any widgets enabled. This would consume disk and processor usage. It is likely that this is pushing your usage above the 'idle' threshold.

**Comment by cmrazek** [comment]
Closing issue.
